package com.technox.audit.entity;

public enum AuditAction {
    MANUAL_REGISTRATION,
    DEADLINE_OVERRIDE,
    CAPACITY_OVERRIDE,
    WAITLIST_APPROVAL,
    ATTENDANCE_CORRECTION,
    EVENT_APPROVAL,
    EVENT_REJECTION,
    EVENT_CANCELLATION,
    USER_STATUS_CHANGE,
    ROLE_CHANGE
}
